---
title: "Tópricos Especias em Ecologia"
output:
  html_document:
    toc: false
---

```{r setup, include=FALSE}
source("setup_knitr.R")
```


<!-- <div class="alert alert-danger" role="alert"> **ATENÇÃO!** Aqui é um -->
<!-- espaço para avisos. Comente quando não utilizar. </div> -->


# <span style="color:#e07a5f">Modelos Lineares Generalizados e Aditivos para Dados Ecológicos </span>


<br>

- **Curso:** Pós-Graduação em Ecologia (PPGECO)

- **Período:** 2025.2

- **Responsável:** [Marie-Christine Rufener][]

- **Contato:** macrufener@gmail.com

- **Horário e Sala:**
    - Segunda à Sexta, 08:30 - 12:00h, [**VER A SALA DE AULA**]{style="color: #dda15e;"}
    
<br>

-----

<br>

# Objetivos da disciplina

A análise quantitativa de dados desempenha um papel fundamental na ecologia moderna, permitindo a investigação de padrões e processos ecológicos com base em informações empíricas e/ou simuladas. Para compreender as relações entre variáveis ecológicas e testar hipóteses de forma robusta, é fundamental o domínio de modelos estatísticos apropriados à complexa natureza dos dados ecológicos.

Esta disciplina tem como objetivo introduzir e aplicar modelos lineares (LM), modelos lineares generalizados (GLM) e modelos aditivos generalizados (GAM) em diferentes contextos ecológicos, oferecendo uma formação teórico e prática que permita ao(a) participante aplicar essas abordagens de maneira crítica e independente em suas pesquisas. A ênfase do curso será na construção, interpretação e validação de modelos em linguagem R. Ao final do curso, espera-se que o (a) discente tenha autonomia para aplicar essas abordagens em problemas ecológicos reais, promovendo análises replicáveis, transparentes e orientadas por hipóteses com embasamento estatístico sólido.


<br>

# Público-alvo

Pós-graduandos e pesquisadores interessados em estatística aplicada e programação.


<br>

# Pré-requisitos da disciplina:

- Ter cursado qualquer disciplina introdutória à (i) inferência estatística e (ii) programação em R (e.g., ECL005, ECL0017)

- Conhecimento básico de análise exploratória de dados (desejável)

<br>

# O que esperar do curso?

- Conhecimento teórico e prático na aplicação de uma classe de modelos estatísticos à diversos contextos ecológicos

- Maior autonomia na escolha, implementação e validação de modelos estatísticos

- Desenvolvimento do pensamento crítico para avaliar os pressupostos bem como as limitações e implicações dos modelos utilizados

- Introdução às boas práticas de reprodutibilidade científica por meio do uso integrado de RStudio, Markdown e GitHub

<br>

# O que não esperar da disciplina?

- Introdução à linguagem de programação R

- Estatística multivariada ou modelos estatísticos mais avançados, como modelos mistos e modelos espaço-temporais

<br>

# Estrutura da disciplina

## Plano de aula

- **Aula 1:** LM \& RMarkdown
- **Aula 2:** Métodos de inferência
- **Aula 3:** GLM para dados binários
- **Aula 4:** GLM para dados discretos
- **Aula 5:** GLM para dados contínuos
- **Aula 6:** GLM para dados categóricos
- **Aula 7:** Distribuições de probabilidade complementares
- **Aula 8:** GAM
- **Aula 9:** GAMLSS
- **Aula 10:** Aula prática: projetos

Cada dia da disciplina será dividida entre aulas teóricas e práticas, de forma que se aprenda a associar a teoria estatística por meio de exercícios práticos.

<br>

## Avaliação

A avaliação da disciplina será baseada na elaboração de um relatório em formato **RMarkdown**, no qual o(a) discente deverá desenvolver um guia prático que cubra todos os tópicos abordados ao longo da disciplina. Para cada tópico, espera-se uma breve exposição teórica, seguida da aplicação prática para a qual o(a) discente deva utilizar preferencialmente seus próprios dados. Além disso, o relatório deverá conter o código comentado, gráficos relevantes e interpretação dos resultados observados.

Caso o(a) discente não disponha de dados próprios, poderá selecionar um dado dentro do conjunto de dados disponibilizados pela professora. 

<br>

## Dúvidas
Envie sua dúvida de programação na sessão [Issues][https://github.com/mcruf/ECL0017-GLM_GAM/issues] do repositório da disciplina no GitHub. Essa abordagem permitirá que suas dúvidas (e respectivas respostas) fiquem disponíveis para os demais discentes, promovendo dessa forma o aprendizado coletivo.

Envie apenas perguntas que possam ser respondidas com uma mensagem breve. Dúvidas que demandem respostas mais detalhadas deverão ser discutidas presencialmente em horário previamente marcado com a professora via e-mail. 

Durante a disciplina, a sessão de `Issues` será verificada diariamente, de segunda a sexta-feira, com uma resposta esperada dentro das primeiras 24 horas.









[Marie-Christine Rufener]: https://mcruf.github.io/

