---
title: "Referências Bibliográficas"
output:
  html_document:
    toc: false
---

<br>


## Referências básicas

- Faraway, J. J. (2014). [Linear Model with R (2nd Ed.)](https://wangyang-bucket.oss-cn-beijing.aliyuncs.com/cms/image/Linear%20Models%20With%20R_1676789263894.pdf). ChapmanHall/CRC.

- Faraway, J. J. (2016). [Extending the Linear Model with R (2nd Ed.)](https://englianhu.wordpress.com/wp-content/uploads/2016/01/faraway-extending-the-linear-model-with-r-e28093-2006.pdf). ChapmanHall/CRC.

- Wood, S. N. (2017). [Generalized Additive Models: An Introduction with R (2nd Ed.)](https://www.taylorfrancis.com/books/mono/10.1201/9781315370279/generalized-additive-models-simon-wood). Chapman and Hall/CRC.

- Zuur, A.F., et al. (2009). [Mixed effects models and extensions in ecology with R](https://link.springer.com/book/10.1007/978-0-387-87458-6). Springer.

<br>



## Referências complementares

- Agresti, A. (2015). [Foundations of Linear and Generalized Linear Models](https://www.amazon.com.br/Foundations-Linear-Generalized-Models/dp/1118730038/ref=sr_1_1?__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=3VGZL6HG9QL16&dib=eyJ2IjoiMSJ9.Hhvti9pShXJLAMbNDTnLioUMcEKe0qGTIHcZkkXP-CJsiZY5VgorzOIUqCGn_zCnqV-HvKI7-1Qq2ewNGnHmTiFpxQiW94tUEfHr2hRuCG7aRkflgZESZfqEmFPlb0EBGKc9cpidnStIyjvJ4dmbDhwZYusTASRdef3MJ7M9NxdDGPwlXWkEAVrXcpTYJ_joEOgf-ok8QH-GP2-CBPM_Rd9gJh1HlIXGzdq7RU0jifg.QFStUnt4HBstE1QLw0dMmldLOMlLOvXMURAnK5E1-uo&dib_tag=se&keywords=Foundations+of+Linear+and+Generalized+Linear+Models&qid=1757417879&s=books&sprefix=%2Cstripbooks%2C217&sr=1-1&ufe=app_do%3Aamzn1.fos.e05b01e0-91a7-477e-a514-15a32325a6d6). Wiley.

- Bolker, B.M. (2008). [Ecological models and data in R](http://www.leg.ufpr.br/lib/exe/fetch.php/wiki:internas:biblioteca:bolker.pdf). Princeton University Press. 

- Clark, M. & Berry, S. (2025) [Models Demystified: A practical guide from linear regression to deep learning](https://m-clark.github.io/book-of-models/) [**Ebook**]

- Da Silva F. R et al. (2022)[Análises Ecológicas no R](https://analises-ecologicas.com/)[**Ebooks**]

- Gelman, A. et al. (2020). [Regression and Other Stories](https://avehtari.github.io/ROS-Examples/). Cambridge University Press.

<!-- - Stasinopoulos et al. (2017). [Flexible Regression and Smoothing -->
<!-- : Using GAMLSS in R.](https://www.taylorfrancis.com/books/mono/10.1201/b21973/flexible-regression-smoothing-mikis-stasinopoulos-robert-rigby-gillian-heller-vlasios-voudouris-fernanda-de-bastiani). Chapman and Hall/CRC. -->



<br>

## Para apreciar com um cafezinho

- Hilborn, R. \& Mangel, M., (2013). [The ecological detective: confronting models with data](http://press.princeton.edu/titles/5987.html). Princeton University Press.

- Mlodinow, L. (2009).[O andar do bêbado. Como o acaso determina nossas vidas](http://zahar.com.br/livro/o-andar-do-b%C3%AAbado). Zahar.


<!-- - Huff, D. -->
<!--   [Como mentir com estatística](http://www.intrinseca.com.br/livro/624/). -->
<!--   Rio de Janeiro: Intrínseca, 2016. -->

<!-- - Salsburg, D. -->
<!--   [Uma senhora toma chá. Como a estatística revolucionou a ciência no século XX](http://www.zahar.com.br/livro/uma-senhora-toma-cha). -->
<!--   Rio de Janeiro: Zahar, 2009. -->
<!-- - Wheelan, C. -->

<!--   [Estatística: o que é, para que serve, como funciona](http://www.zahar.com.br/livro/estatistica). -->
<!--   Rio de Janeiro: Zahar, 2016. -->
